### ISSUE TITLE
Motor stutters @ 50 % only when closing

### ISSUE THREAD

**Issue by hansgans007** [mjuhanne/fyrtur-motor-board#3] opened 2021-01-30 10:05 UTC
But when I open the blind it doesnt stutter 

Maybe u know why ? 

Can i do something because i dont want to buy a new one ?

**Comment by mjuhanne** [comment] 2021-01-30 18:56
Hi,
by stuttering you mean that it stops for few milliseconds and then continues?  If  you have more than one blinds, can you test if it happens with all of them? 

Does it happen with both the original motor firmware and my custom one? (and you are using the latest version?) 

What voltage are you using? Also, make sure that the power supply can supply at least 1 amp (preferably 2 amps).

**Comment by hansgans007** [comment] 2021-01-30 19:45
https://user-images.githubusercontent.com/76871070/106366440-1c5d5b80-633c-11eb-8bcf-76cd3792f3d2.MOV

Yes with both firmwares.

and only appears when closing ( @ 50 % ) 

From 0-49% it’s smooth 

50%-100% stutter 

from 100-0% it’s smooth also 

the powersupply makes 7.5V / 2A that’s enough.

**Comment by hansgans007** [comment] 2021-01-30 19:47
the 2nd blind don’t do it

**Comment by mjuhanne** [comment] 2021-01-30 21:22
Ouch, that clacking sound sounds quite nasty! Are you sure there's not some kind of mechanical obstruction there? 
Because there's no problem with your 2nd blind, and because the problem is with both custom/original motor firmware, then that proves it's not an issue with the firmware itself.

**Comment by hansgans007** [comment] 2021-02-01 17:04
When it drives up no Problem only @50% when it goes down 

u also dont have a solution ?

**Comment by mjuhanne** [comment] 2022-04-10 19:39
You could try the newer versions, but I suspect this is some kind of mechanical problem. Closing.

**Closed as completed by mjuhanne** 2022-04-10 19:39 UTC
